### ISSUE TITLE
chown: changing ownership of '/var/www/owncloud/config': Operation not permitted

### ISSUE THREAD

**Issue by badu013** [vnc-biz/owncloud#3]
when i'm installing `owncloud` helm chart with persistent volume enabled with EFS, I'm getting this issue.

here is pod logs
```
Creating volume folders...
Creating hook folders...
Waiting for MySQL...
services are ready!
Removing custom folder...
Linking custom folder...
Removing config folder...
Linking config folder...
Writing config file...
Fixing base perms...
chown: changing ownership of '/var/www/owncloud/custom': Operation not permitted
chown: changing ownership of '/var/www/owncloud/config': Operation not permitted

```
pod status:
```

NAME                        READY   STATUS             RESTARTS   AGE
owncloud-66966b7db6-5rxvm   0/1     CrashLoopBackOff   1          17s
```
storageclass.yaml

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: owncloud-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxx
  directoryPerms: "777"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/owncloud-efs" # optional
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
pv-pvc.yaml

```
{{- if .Values.persistence.owncloud.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "owncloud.fullname" . }}
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  storageClassName: {{ .Values.persistence.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxxxxxx
{{end}}
---
{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "owncloud.fullname" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: {{ .Values.persistence.storageClassName }}
```
